# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'NASA APP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Nuke', '~> 7.0'
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'IQKeyboardManager'
  
target 'NASA APPTests' do
    inherit! :search_paths
    pod 'Nuke', '~> 7.0'
    pod 'Alamofire', '~> 5.0.0-beta.5'
    pod 'IQKeyboardManager'
  end

end
